services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - appdata:/app/data
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    restart: unless-stopped
volumes:
  appdata:
